# Generated by Django 3.1.7 on 2021-04-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20210403_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='memo',
            field=models.TextField(),
        ),
    ]
