# Generated by Django 3.1.7 on 2021-04-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('SR', 'Secretary'), ('EX', 'Executive')], default='EX', max_length=2),
        ),
    ]
