# Generated by Django 3.1.7 on 2021-04-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_useraccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('SE', 'secretary'), ('EX', 'executive')], default='EX', max_length=2),
        ),
    ]
