# Generated by Django 3.1.7 on 2021-04-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='attended',
            field=models.IntegerField(default=0),
        ),
    ]
