# Generated by Django 3.1.7 on 2021-04-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meeting_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
